name: Build

concurrency: 
  group: "build"
  cancel-in-progress: true

on:
  push:
    branches:
      - master
      - main
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório principal
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: "src"

      # Cria a pasta builds
      - name: Create builds folder
        run: mkdir -p $GITHUB_WORKSPACE/builds

      # Limpa builds antigos
      - name: Clean old builds
        run: rm -f $GITHUB_WORKSPACE/builds/*.cs3

      # Setup JDK 17
      - name: Setup JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      # Setup Android SDK
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      # Build Plugins
      - name: Build Plugins
        run: |
          cd $GITHUB_WORKSPACE/src
          chmod +x gradlew
          ./gradlew make makePluginsJson
          cp **/build/*.cs3 $GITHUB_WORKSPACE/builds || true
          cp build/plugins.json $GITHUB_WORKSPACE/builds || true

      # Commit e push dos builds
      - name: Push builds
        run: |
          cd $GITHUB_WORKSPACE/builds
          git init
          git remote add origin ${{ github.repositoryUrl }}
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Build $GITHUB_SHA" || exit 0
          git push -f origin main
